// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY-gbxtE51u75F4VZ-cvICa1nyAtTSjVY',
    appId: '1:783034806741:web:bf6bda7f3e8aa27240cd5c',
    messagingSenderId: '783034806741',
    projectId: 'skin-cancer-product',
    authDomain: 'skin-cancer-product.firebaseapp.com',
    storageBucket: 'skin-cancer-product.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAPjqhh79oqxx0tGElCy0E-M1zQ-VHOyag',
    appId: '1:783034806741:android:ee443ad99961651440cd5c',
    messagingSenderId: '783034806741',
    projectId: 'skin-cancer-product',
    storageBucket: 'skin-cancer-product.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAQt4bN8KyKKikooKl-1FKE8g0Dw6KJntY',
    appId: '1:783034806741:ios:f1ff1b947af32e1d40cd5c',
    messagingSenderId: '783034806741',
    projectId: 'skin-cancer-product',
    storageBucket: 'skin-cancer-product.appspot.com',
    iosBundleId: 'com.example.skinCancerAppFinal',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAQt4bN8KyKKikooKl-1FKE8g0Dw6KJntY',
    appId: '1:783034806741:ios:464e3ee9d60f52db40cd5c',
    messagingSenderId: '783034806741',
    projectId: 'skin-cancer-product',
    storageBucket: 'skin-cancer-product.appspot.com',
    iosBundleId: 'com.example.skinCancerAppFinal.RunnerTests',
  );
}
